// Generated by CoffeeScript 1.6.2
(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  $(document).ready(function() {
    var betAmount, documentHeight, finishTable, firstRoll, handleResults, hideInstructions, howToHandle, instructionsTimeoutID, isWorkerPaused, isWorkerRunningIndefinitely, justKeepPlaying, lastNumWins, newTable, newTableIndefinitely, numVisitsToSite, oddsPayout, pauseWorker, playCrapsAndHandleResults, polyglot, rollsPerTable, runningTotal, saveToLocalStorage, secondRoll, showInstructions, showInstructionsInAMoment, showTotal, storedObject, storyFileForThisVisit, storyFiles, tellNextLine, tellStory, totalWins, updateHeader, updateRunningTotal, whichChapter, wonAtFirstTable, wonFirstOrSecondRoll, worker;

    betAmount = 5;
    oddsPayout = 30;
    rollsPerTable = 20;
    numVisitsToSite = 0;
    runningTotal = 0;
    lastNumWins = 0;
    totalWins = 0;
    wonFirstOrSecondRoll = false;
    wonAtFirstTable = false;
    instructionsTimeoutID = 0;
    howToHandle = "";
    documentHeight = 0;
    isWorkerRunningIndefinitely = false;
    isWorkerPaused = false;
    polyglot = new Polyglot;
    if (localStorage && localStorage.getItem("boxcars")) {
      storedObject = JSON.parse(localStorage.getItem("boxcars"));
      betAmount = storedObject.betAmount;
      oddsPayout = storedObject.oddsPayout;
      rollsPerTable = storedObject.rollsPerTable;
      numVisitsToSite = storedObject.numVisitsToSite;
    }
    saveToLocalStorage = function() {
      var objectToStore;

      if (!localStorage) {
        return;
      }
      objectToStore = {
        betAmount: betAmount,
        oddsPayout: oddsPayout,
        rollsPerTable: rollsPerTable,
        numVisitsToSite: numVisitsToSite
      };
      return localStorage.setItem("boxcars", JSON.stringify(objectToStore));
    };
    handleResults = function(numRolls, numWins, rollResults, howToHandle) {
      var $div, losses, tableTotal, total, winnings, wonOrLost;

      lastNumWins = numWins;
      totalWins += numWins;
      losses = (numRolls - numWins) * betAmount;
      winnings = numWins * betAmount * oddsPayout;
      total = winnings - losses;
      updateRunningTotal(total);
      if (howToHandle === "firstRoll" || howToHandle === "newTable") {
        $div = $("<div>").appendTo("article");
      } else {
        $div = $("article div").last();
      }
      if (rollResults !== "") {
        $div.append(rollResults);
        if (howToHandle === "finishTable" || howToHandle === "newTable") {
          tableTotal = howToHandle === "finishTable" ? runningTotal : total;
          wonOrLost = formatWinOrLoss(tableTotal, "Won " + (formatCurrency(tableTotal)), "Lost " + (formatCurrency(-tableTotal)), "Broke even");
          $("<label>").text(wonOrLost.text).addClass(wonOrLost.result).appendTo($div);
        }
        if (documentHeight !== $(document).height()) {
          documentHeight = $(document).height();
          return $.scrollTo($div, 500, {
            offset: -$("header").outerHeight()
          });
        }
      }
    };
    updateHeader = function(text) {
      return $("header").html(text);
    };
    showInstructionsInAMoment = function() {
      return instructionsTimeoutID = setTimeout(showInstructions, 3000);
    };
    showInstructions = function() {
      return $(".instructions").fadeIn(500);
    };
    hideInstructions = function() {
      clearTimeout(instructionsTimeoutID);
      return $(".instructions").fadeOut(250);
    };
    showTotal = function() {
      return $("footer").delay(1000).fadeIn(600);
    };
    worker = new Worker("js/playCrapsWorker.js");
    worker.addEventListener("message", function(e) {
      return handleResults(e.data.numRolls, e.data.numWins, e.data.rollResults, howToHandle);
    }, false);
    playCrapsAndHandleResults = function(numRolls) {
      var results;

      results = playCraps(numRolls, true);
      return handleResults(results.numRolls, results.numWins, results.rollResults, howToHandle);
    };
    firstRoll = function() {
      howToHandle = "firstRoll";
      return playCrapsAndHandleResults(1);
    };
    secondRoll = function() {
      howToHandle = "secondRoll";
      return playCrapsAndHandleResults(1);
    };
    finishTable = function() {
      howToHandle = "finishTable";
      return playCrapsAndHandleResults(rollsPerTable - 2);
    };
    newTable = function() {
      howToHandle = "newTable";
      return playCrapsAndHandleResults(rollsPerTable);
    };
    newTableIndefinitely = function(fastOrSlow) {
      howToHandle = "newTable";
      return worker.postMessage({
        command: "playCraps",
        numRolls: rollsPerTable,
        returnAllRolls: true,
        delay: fastOrSlow === "fast" ? 100 : 1000
      });
    };
    justKeepPlaying = function() {
      howToHandle = "justKeepPlaying";
      isWorkerPaused = false;
      isWorkerRunningIndefinitely = true;
      return worker.postMessage({
        command: "playCraps",
        numRolls: 1,
        returnAllRolls: false,
        delay: 10
      });
    };
    pauseWorker = function() {
      isWorkerPaused = true;
      isWorkerRunningIndefinitely = false;
      return worker.postMessage({
        command: "pause"
      });
    };
    $(document).on("keyup", function(e) {
      if (e.keyCode === 27) {
        if (isWorkerRunningIndefinitely) {
          return pauseWorker();
        } else if (isWorkerPaused) {
          return justKeepPlaying();
        }
      }
    });
    updateRunningTotal = function(newTotal) {
      var runningWinOrLoss;

      runningTotal += newTotal;
      runningWinOrLoss = formatWinOrLoss(runningTotal, "You've won a total of " + (formatCurrency(runningTotal)), "You've lost a total of " + (formatCurrency(-runningTotal)), "You're even");
      return $("footer").text(runningWinOrLoss.text).removeClass().addClass(runningWinOrLoss.result);
    };
    whichChapter = 1;
    tellStory = function() {
      var noEndingPartNumber, _i, _results;

      switch (whichChapter) {
        case 1:
          tellNextLine("intro.1");
          showInstructionsInAMoment();
          break;
        case 2:
          tellNextLine("intro.2", {
            betAmount: formatCurrency(betAmount)
          });
          hideInstructions();
          break;
        case 3:
          tellNextLine("intro.3");
          break;
        case 4:
          tellNextLine("intro.4");
          break;
        case 5:
          firstRoll();
          if (lastNumWins === 1) {
            wonFirstOrSecondRoll = true;
            tellNextLine("firstRoll.won", {
              betAmount: formatCurrency(betAmount),
              oneBetWinnings: formatCurrency(betAmount * oddsPayout)
            });
          } else {
            tellNextLine("firstRoll.lost");
          }
          break;
        case 6:
          secondRoll();
          if (lastNumWins === 1) {
            wonFirstOrSecondRoll = true;
            if (totalWins === 2) {
              tellNextLine("secondRoll.wonBoth");
            } else {
              tellNextLine("secondRoll.wonSecondLostFirst");
            }
          } else {
            if (totalWins === 1) {
              tellNextLine("secondRoll.wonFirstLostSecond");
            } else {
              tellNextLine("secondRoll.lostBoth");
            }
          }
          break;
        case 7:
          finishTable();
          switch (false) {
            case !(wonFirstOrSecondRoll && lastNumWins > 0):
              tellNextLine("firstTable.wonFirstRollsAndWonAgain");
              break;
            case !(wonFirstOrSecondRoll && lastNumWins === 0):
              tellNextLine("firstTable.wonFirstRollsButLostTheRest");
              break;
            case !(!wonFirstOrSecondRoll && lastNumWins > 1):
              tellNextLine("firstTable.lostFirstRollsButWonMoreThanOne");
              break;
            case !(!wonFirstOrSecondRoll && lastNumWins === 1):
              tellNextLine("firstTable.lostFirstRollsButWonOne");
              break;
            case !(!wonFirstOrSecondRoll && lastNumWins === 0):
              tellNextLine("firstTable.lostAllRolls");
          }
          wonAtFirstTable = totalWins > 0;
          showTotal();
          break;
        case 8:
          newTable();
          switch (false) {
            case !(wonAtFirstTable && lastNumWins > 0):
              tellNextLine("secondTable.wonBoth");
              break;
            case !(wonAtFirstTable && lastNumWins === 0):
              tellNextLine("secondTable.wonFirstLostSecond");
              break;
            case !(!wonAtFirstTable && lastNumWins > 0):
              tellNextLine("secondTable.wonSecondLostFirst");
              break;
            case !(!wonAtFirstTable && lastNumWins === 0):
              tellNextLine("secondTable.lostBoth");
          }
          break;
        case 9:
          newTableIndefinitely("slow");
          tellNextLine("keepPlaying.tablesSlow");
          break;
        case 10:
          newTableIndefinitely("fast");
          tellNextLine("keepPlaying.tablesFast");
          break;
        case 11:
          justKeepPlaying();
          tellNextLine("keepPlaying.rolls");
          break;
        default:
          if (__indexOf.call((function() {
            _results = [];
            for (_i = 11; _i <= 58; _i++){ _results.push(_i); }
            return _results;
          }).apply(this), whichChapter) >= 0) {
            noEndingPartNumber = whichChapter - 11;
            tellNextLine("noEnding." + noEndingPartNumber);
          }
      }
      return whichChapter++;
    };
    tellNextLine = function(storyKey, extraValues) {
      extraValues = extraValues != null ? extraValues : {};
      return updateHeader(polyglot.t(storyKey, extraValues));
    };
    $(document).on("keyup", function(e) {
      var _ref;

      if ((_ref = e.keyCode) === 13 || _ref === 39 || _ref === 32) {
        return tellStory();
      }
    });
    $(document).on("click", "header", tellStory);
    numVisitsToSite++;
    storyFiles = ["vegas", "atlantic-city"];
    storyFileForThisVisit = storyFiles[(numVisitsToSite - 1) % 2];
    saveToLocalStorage();
    return $.getJSON("story/" + storyFileForThisVisit + ".json", function(data) {
      polyglot.extend(data);
      return $.getJSON("story/no-ending.json", function(data) {
        polyglot.extend(data);
        return tellStory();
      });
    });
  });

}).call(this);
