// Generated by CoffeeScript 1.6.2
(function() {
  $(document).ready(function() {
    var betAmount, currentEndingLastLineNumber, documentHeight, endingFileForThisVisit, endingFiles, finishTable, firstRoll, handleResults, hasLastEndingSeenBeenIncremented, hideInstructions, howToHandle, incrementLastEndingSeen, instructionsTimeoutID, isWorkerPaused, isWorkerRunningIndefinitely, justKeepPlaying, lastEndingSeen, lastNumWins, newTable, newTableIndefinitely, numVisitsToSite, oddsPayout, pauseWorker, playCrapsAndHandleResults, polyglot, queryString, queryStringValues, rollsPerTable, runningTotal, saveToLocalStorage, sayNextLine, secondRoll, showInstructions, showInstructionsInAMoment, showTotal, storedObject, storyFileForThisVisit, storyFiles, tellStory, totalWins, updateHeader, updateRunningTotal, whichChapter, wonAtFirstTable, wonFirstOrSecondRoll, worker, _ref, _ref1, _ref2;

    betAmount = 5;
    oddsPayout = 30;
    rollsPerTable = 20;
    numVisitsToSite = 0;
    lastEndingSeen = 0;
    hasLastEndingSeenBeenIncremented = false;
    currentEndingLastLineNumber = 0;
    runningTotal = 0;
    lastNumWins = 0;
    totalWins = 0;
    wonFirstOrSecondRoll = false;
    wonAtFirstTable = false;
    instructionsTimeoutID = 0;
    howToHandle = "";
    documentHeight = 0;
    isWorkerRunningIndefinitely = false;
    isWorkerPaused = false;
    polyglot = new Polyglot;
    if (localStorage && localStorage.getItem("boxcars")) {
      storedObject = JSON.parse(localStorage.getItem("boxcars"));
      betAmount = storedObject.betAmount;
      oddsPayout = storedObject.oddsPayout;
      rollsPerTable = storedObject.rollsPerTable;
      numVisitsToSite = storedObject.numVisitsToSite;
      lastEndingSeen = storedObject.lastEndingSeen;
    }
    saveToLocalStorage = function() {
      var objectToStore;

      if (!localStorage) {
        return;
      }
      objectToStore = {
        betAmount: betAmount,
        oddsPayout: oddsPayout,
        rollsPerTable: rollsPerTable,
        numVisitsToSite: numVisitsToSite,
        lastEndingSeen: lastEndingSeen
      };
      return localStorage.setItem("boxcars", JSON.stringify(objectToStore));
    };
    handleResults = function(numRolls, numWins, rollResults, howToHandle) {
      var $div, losses, tableTotal, total, winnings, wonOrLost;

      lastNumWins = numWins;
      totalWins += numWins;
      losses = (numRolls - numWins) * betAmount;
      winnings = numWins * betAmount * oddsPayout;
      total = winnings - losses;
      updateRunningTotal(total);
      if (howToHandle === "firstRoll" || howToHandle === "newTable") {
        $div = $("<div>").appendTo("article");
      } else {
        $div = $("article div").last();
      }
      if (rollResults !== "") {
        $div.append(rollResults);
        if (howToHandle === "finishTable" || howToHandle === "newTable") {
          tableTotal = howToHandle === "finishTable" ? runningTotal : total;
          wonOrLost = formatWinOrLoss(tableTotal, "Won " + (formatCurrency(tableTotal)), "Lost " + (formatCurrency(-tableTotal)), "Broke even");
          $("<label>").text(wonOrLost.text).addClass(wonOrLost.result).appendTo($div);
        }
        if (documentHeight !== $(document).height()) {
          documentHeight = $(document).height();
          return $.scrollTo($div, 500, {
            offset: -$("header").outerHeight()
          });
        }
      }
    };
    updateHeader = function(text) {
      return $("header").html(text);
    };
    showInstructionsInAMoment = function() {
      return instructionsTimeoutID = setTimeout(showInstructions, 3000);
    };
    showInstructions = function() {
      return $(".instructions").fadeIn(500);
    };
    hideInstructions = function() {
      clearTimeout(instructionsTimeoutID);
      return $(".instructions").fadeOut(250);
    };
    showTotal = function() {
      return $("footer").delay(1000).fadeIn(600);
    };
    worker = new Worker("js/playCrapsWorker.js");
    worker.addEventListener("message", function(e) {
      return handleResults(e.data.numRolls, e.data.numWins, e.data.rollResults, howToHandle);
    }, false);
    playCrapsAndHandleResults = function(numRolls) {
      var results;

      results = playCraps(numRolls, true);
      return handleResults(results.numRolls, results.numWins, results.rollResults, howToHandle);
    };
    firstRoll = function() {
      howToHandle = "firstRoll";
      return playCrapsAndHandleResults(1);
    };
    secondRoll = function() {
      howToHandle = "secondRoll";
      return playCrapsAndHandleResults(1);
    };
    finishTable = function() {
      howToHandle = "finishTable";
      return playCrapsAndHandleResults(rollsPerTable - 2);
    };
    newTable = function() {
      howToHandle = "newTable";
      return playCrapsAndHandleResults(rollsPerTable);
    };
    newTableIndefinitely = function(fastOrSlow) {
      howToHandle = "newTable";
      return worker.postMessage({
        command: "playCraps",
        numRolls: rollsPerTable,
        returnAllRolls: true,
        delay: fastOrSlow === "fast" ? 100 : 1000
      });
    };
    justKeepPlaying = function() {
      howToHandle = "justKeepPlaying";
      isWorkerPaused = false;
      isWorkerRunningIndefinitely = true;
      return worker.postMessage({
        command: "playCraps",
        numRolls: 1,
        returnAllRolls: false,
        delay: 10
      });
    };
    pauseWorker = function() {
      isWorkerPaused = true;
      isWorkerRunningIndefinitely = false;
      return worker.postMessage({
        command: "pause"
      });
    };
    $(document).on("keyup", function(e) {
      if (e.keyCode === 27) {
        if (isWorkerRunningIndefinitely) {
          return pauseWorker();
        } else if (isWorkerPaused) {
          return justKeepPlaying();
        }
      }
    });
    updateRunningTotal = function(newTotal) {
      var runningWinOrLoss;

      runningTotal += newTotal;
      runningWinOrLoss = formatWinOrLoss(runningTotal, "You've won a total of " + (formatCurrency(runningTotal)), "You've lost a total of " + (formatCurrency(-runningTotal)), "You're even");
      return $("footer").text(runningWinOrLoss.text).removeClass().addClass(runningWinOrLoss.result);
    };
    whichChapter = 1;
    tellStory = function() {
      var endingPartNumber;

      switch (whichChapter) {
        case 1:
          sayNextLine("intro.1");
          showInstructionsInAMoment();
          break;
        case 2:
          sayNextLine("intro.2", {
            betAmount: formatCurrency(betAmount)
          });
          hideInstructions();
          break;
        case 3:
          sayNextLine("intro.3");
          break;
        case 4:
          sayNextLine("intro.4");
          break;
        case 5:
          firstRoll();
          if (lastNumWins === 1) {
            wonFirstOrSecondRoll = true;
            sayNextLine("firstRoll.won", {
              betAmount: formatCurrency(betAmount),
              oneBetWinnings: formatCurrency(betAmount * oddsPayout)
            });
          } else {
            sayNextLine("firstRoll.lost");
          }
          break;
        case 6:
          secondRoll();
          if (lastNumWins === 1) {
            wonFirstOrSecondRoll = true;
            if (totalWins === 2) {
              sayNextLine("secondRoll.wonBoth");
            } else {
              sayNextLine("secondRoll.wonSecondLostFirst");
            }
          } else {
            if (totalWins === 1) {
              sayNextLine("secondRoll.wonFirstLostSecond");
            } else {
              sayNextLine("secondRoll.lostBoth");
            }
          }
          break;
        case 7:
          finishTable();
          switch (false) {
            case !(wonFirstOrSecondRoll && lastNumWins > 0):
              sayNextLine("firstTable.wonFirstRollsAndWonAgain");
              break;
            case !(wonFirstOrSecondRoll && lastNumWins === 0):
              sayNextLine("firstTable.wonFirstRollsButLostTheRest");
              break;
            case !(!wonFirstOrSecondRoll && lastNumWins > 1):
              sayNextLine("firstTable.lostFirstRollsButWonMoreThanOne");
              break;
            case !(!wonFirstOrSecondRoll && lastNumWins === 1):
              sayNextLine("firstTable.lostFirstRollsButWonOne");
              break;
            case !(!wonFirstOrSecondRoll && lastNumWins === 0):
              sayNextLine("firstTable.lostAllRolls");
          }
          wonAtFirstTable = totalWins > 0;
          showTotal();
          break;
        case 8:
          newTable();
          switch (false) {
            case !(wonAtFirstTable && lastNumWins > 0):
              sayNextLine("secondTable.wonBoth");
              break;
            case !(wonAtFirstTable && lastNumWins === 0):
              sayNextLine("secondTable.wonFirstLostSecond");
              break;
            case !(!wonAtFirstTable && lastNumWins > 0):
              sayNextLine("secondTable.wonSecondLostFirst");
              break;
            case !(!wonAtFirstTable && lastNumWins === 0):
              sayNextLine("secondTable.lostBoth");
          }
          break;
        case 9:
          newTableIndefinitely("slow");
          sayNextLine("keepPlaying.tablesSlow");
          break;
        case 10:
          newTableIndefinitely("fast");
          sayNextLine("keepPlaying.tablesFast");
          break;
        case 11:
          justKeepPlaying();
          sayNextLine("keepPlaying.rolls");
          break;
        default:
          endingPartNumber = whichChapter - 11;
          if (endingPartNumber <= currentEndingLastLineNumber) {
            sayNextLine("ending." + endingPartNumber);
          }
          if (endingPartNumber >= currentEndingLastLineNumber || endingPartNumber > 31) {
            incrementLastEndingSeen();
          }
      }
      return whichChapter++;
    };
    sayNextLine = function(storyKey, extraValues) {
      extraValues = extraValues != null ? extraValues : {};
      return updateHeader(polyglot.t(storyKey, extraValues));
    };
    $(document).on("keyup", function(e) {
      var _ref;

      if ((_ref = e.keyCode) === 13 || _ref === 39 || _ref === 32) {
        return tellStory();
      }
    });
    $(document).on("click", "header", tellStory);
    numVisitsToSite++;
    storyFiles = ["vegas", "atlantic-city"];
    storyFileForThisVisit = storyFiles[(numVisitsToSite - 1) % 2];
    endingFiles = ["first-ending", "second-ending"];
    endingFileForThisVisit = endingFiles[lastEndingSeen % 2];
    incrementLastEndingSeen = function() {
      if (hasLastEndingSeenBeenIncremented) {
        return;
      }
      hasLastEndingSeenBeenIncremented = true;
      lastEndingSeen++;
      return saveToLocalStorage();
    };
    if (location.search) {
      queryString = location.search.indexOf("?") === 0 ? location.search.substring(1) : location.search;
      queryStringValues = $.deserialize(queryString);
      betAmount = (_ref = queryStringValues.betAmount) != null ? _ref : betAmount;
      oddsPayout = (_ref1 = queryStringValues.oddsPayout) != null ? _ref1 : oddsPayout;
      rollsPerTable = (_ref2 = queryStringValues.rollsPerTable) != null ? _ref2 : rollsPerTable;
    }
    saveToLocalStorage();
    return $.getJSON("story/stories/" + storyFileForThisVisit + ".json", function(data) {
      polyglot.extend(data);
      return $.getJSON("story/endings/" + endingFileForThisVisit + ".json", function(data) {
        polyglot.extend(data);
        currentEndingLastLineNumber = data.lastLineNumber;
        return tellStory();
      });
    });
  });

}).call(this);
