// Generated by CoffeeScript 1.6.2
(function() {
  var context;

  context = typeof window !== "undefined" && window !== null ? window : self;

  context.rollDie = function() {
    return Math.floor(Math.random() * 6) + 1;
  };

  context.rollPairOfDice = function() {
    var i, _i, _results;

    _results = [];
    for (i = _i = 0; _i <= 1; i = ++_i) {
      _results.push(rollDie());
    }
    return _results;
  };

  context.playCraps = function(numRolls, returnAllRolls) {
    var i, newRoll, numWins, rollResults, thisRollWon, _i;

    numWins = 0;
    rollResults = "";
    for (i = _i = 1; _i <= numRolls; i = _i += 1) {
      thisRollWon = false;
      newRoll = rollPairOfDice();
      if (newRoll[0] + newRoll[1] === 12) {
        thisRollWon = true;
        numWins++;
      }
      if (returnAllRolls) {
        rollResults += "<span" + (thisRollWon ? " class='boxcars'" : "") + ("> " + (newRoll.join()) + " </span>");
      }
    }
    return {
      numRolls: numRolls,
      numWins: numWins,
      rollResults: rollResults
    };
  };

}).call(this);
