// Generated by CoffeeScript 1.6.2
(function() {
  var context;

  context = typeof window !== "undefined" && window !== null ? window : self;

  context.rollDie = function(oddsOfRollingASix) {
    if (oddsOfRollingASix === "normal") {
      return Math.floor(Math.random() * 6) + 1;
    } else {
      if (Math.random() < oddsOfRollingASix) {
        return 6;
      } else {
        return Math.floor(Math.random() * 5) + 1;
      }
    }
  };

  context.rollPairOfDice = function(oddsOfRollingASix) {
    var i, _i, _results;

    _results = [];
    for (i = _i = 0; _i <= 1; i = ++_i) {
      _results.push(rollDie(oddsOfRollingASix));
    }
    return _results;
  };

  context.playCraps = function(numRolls, returnAllRolls, oddsOfRollingASix) {
    var i, newRoll, numWins, rollResults, thisRollWon, _i;

    oddsOfRollingASix = oddsOfRollingASix != null ? oddsOfRollingASix : "normal";
    numWins = 0;
    rollResults = "";
    for (i = _i = 1; _i <= numRolls; i = _i += 1) {
      thisRollWon = false;
      newRoll = rollPairOfDice(oddsOfRollingASix);
      if (newRoll[0] + newRoll[1] === 12) {
        thisRollWon = true;
        numWins++;
      }
      if (returnAllRolls) {
        rollResults += "<span" + (thisRollWon ? " class='boxcars'" : "") + ("> " + (newRoll.join()) + " </span>");
      }
    }
    return {
      numRolls: numRolls,
      numWins: numWins,
      rollResults: rollResults
    };
  };

}).call(this);
