// Generated by CoffeeScript 1.6.2
(function() {
  var intervalID;

  importScripts("playCraps.js");

  intervalID = 0;

  self.addEventListener("message", function(e) {
    var command, delay, numRolls, returnAllRolls, _ref, _ref1, _ref2;

    if (intervalID) {
      clearInterval(intervalID);
    }
    command = e.data.command;
    numRolls = (_ref = e.data.numRolls) != null ? _ref : 0;
    returnAllRolls = (_ref1 = e.data.returnAllRolls) != null ? _ref1 : false;
    delay = (_ref2 = e.data.delay) != null ? _ref2 : 10;
    if (command === "playCraps") {
      self.postMessage(playCraps(numRolls, returnAllRolls));
      return intervalID = setInterval(function() {
        return self.postMessage(playCraps(numRolls, returnAllRolls));
      }, delay);
    }
  }, false);

}).call(this);
