// Generated by CoffeeScript 1.6.2
(function() {
  window.formatCurrency = function(amount) {
    if (amount < 0) {
      return "-$" + -amount;
    } else {
      return "$" + amount;
    }
  };

  window.formatWinOrLoss = function(amountWonOrLost, wonText, lostText, evenText) {
    switch (false) {
      case amountWonOrLost !== 0:
        return {
          text: evenText,
          result: "even"
        };
      case !(amountWonOrLost > 0):
        return {
          text: wonText,
          result: "won"
        };
      case !(amountWonOrLost < 0):
        return {
          text: lostText,
          result: "lost"
        };
    }
  };

}).call(this);
