// Generated by CoffeeScript 1.6.2
(function() {
  window.formatCurrency = function(amount) {
    if (amount < 0) {
      return "-$" + -amount;
    } else {
      return "$" + amount;
    }
  };

  window.formatWinOrLoss = function(amountWonOrLost, wonText, lostText, evenText, smallWinOrLossThreshold, wonALittleText, lostALittleText) {
    smallWinOrLossThreshold = smallWinOrLossThreshold != null ? smallWinOrLossThreshold : 0;
    wonALittleText = wonALittleText != null ? wonALittleText : wonText;
    lostALittleText = lostALittleText != null ? lostALittleText : lostText;
    switch (false) {
      case amountWonOrLost !== 0:
        return {
          text: evenText,
          result: "even"
        };
      case !(amountWonOrLost > 0):
        if (amountWonOrLost > smallWinOrLossThreshold) {
          return {
            text: wonText,
            result: "won"
          };
        } else {
          return {
            text: wonALittleText,
            result: "wonALittle"
          };
        }
        break;
      case !(amountWonOrLost < 0):
        if (amountWonOrLost < -smallWinOrLossThreshold) {
          return {
            text: lostText,
            result: "lost"
          };
        } else {
          return {
            text: lostALittleText,
            result: "lostALittle"
          };
        }
    }
  };

}).call(this);
